# Generated by Django 5.1.1 on 2024-10-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('number_plate', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('stop_latitude', models.FloatField()),
                ('stop_longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'Emergency Vehicle',
                'verbose_name_plural': 'Emergency Vehicles',
            },
        ),
    ]
